### ISSUE TITLE
关于在decoder中添加tlm的问题

### ISSUE THREAD

**Issue by jiayidengYumy** [Young1993/tlm#1]
您好，我仔细阅读了您的论文，您在bart中分别在encoder和decoder中均添加了掩码，我不太理解的是如何在decoder中运用的tlm策略，因为transformer架构中decoder部分是由masked attention和cross attention两部分，同encoder中self attention不一致，我想向您问一下如何在decoder中添加的tlm掩码部分，您能给出decoder部分tlm的代码吗

**Comment by Young1993** [comment]
> 您好，我仔细阅读了您的论文，您在bart中分别在encoder和decoder中均添加了掩码，我不太理解的是如何在decoder中运用的tlm策略，因为transformer架构中decoder部分是由masked attention和cross attention两部分，同encoder中self attention不一致，我想向您问一下如何在decoder中添加的tlm掩码部分，您能给出decoder部分tlm的代码吗

哈喽，代码我已经更新了哈，如果你还有问题，可以再提issue哈。
